### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by MacklemoreLover9000** [gr-sb/squarebracket#104]
**Describe the bug**
You suck

**To Reproduce**
1. Go to 'qaurebracket.com'
2. Click on 'register'
3. Scroll down to register button'

**Expected behavior**
you turn into a 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy A50]
 - OS: [e.g. Android 11]
 - Browser [e.g. Firefox]
 - Version [e.g. 94]

**Additional context**

**Comment by rollerozxa** [comment]
no u

**Comment by chaziz94** [comment]
HAHAHA
