### ISSUE TITLE
Upload failure rate is alarmy higher

### ISSUE THREAD

**Issue by chaziz94** [gr-sb/squarebracket#63]
https://web.archive.org/web/20210804161948/https://squarebracket.veselcraft.ru/watch.php?v=O--zZ_FmMD-

https://web.archive.org/web/20210804161948/https://squarebracket.veselcraft.ru/watch.php?v=BTZjNGFuZj_

https://web.archive.org/web/20210804161948/https://squarebracket.veselcraft.ru/watch.php?v=M-_l-Tpl_JJ

these videos were uploaded 2 hours prior of taking the wayback snapshot. they appear to have fucked up

**Comment by forkiesassds** [comment]
might've been some quirk on production

**Comment by chaziz94** [comment]
pretty sure it was
